// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ChatMessageTmp.proto

package proto_gen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMessage struct {
	Message              *string  `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	Time                 *int64   `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	ChatPerson           *string  `protobuf:"bytes,3,req,name=chatPerson" json:"chatPerson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d4f5b9c2cc7ae31, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ChatMessage) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *ChatMessage) GetChatPerson() string {
	if m != nil && m.ChatPerson != nil {
		return *m.ChatPerson
	}
	return ""
}

type ChatMessageList struct {
	ChatMessages         []*ChatMessage `protobuf:"bytes,1,rep,name=chatMessages" json:"chatMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChatMessageList) Reset()         { *m = ChatMessageList{} }
func (m *ChatMessageList) String() string { return proto.CompactTextString(m) }
func (*ChatMessageList) ProtoMessage()    {}
func (*ChatMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d4f5b9c2cc7ae31, []int{1}
}

func (m *ChatMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessageList.Unmarshal(m, b)
}
func (m *ChatMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessageList.Marshal(b, m, deterministic)
}
func (m *ChatMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessageList.Merge(m, src)
}
func (m *ChatMessageList) XXX_Size() int {
	return xxx_messageInfo_ChatMessageList.Size(m)
}
func (m *ChatMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessageList proto.InternalMessageInfo

func (m *ChatMessageList) GetChatMessages() []*ChatMessage {
	if m != nil {
		return m.ChatMessages
	}
	return nil
}

type ChatMessageListServiceStatus struct {
	OK                   *bool    `protobuf:"varint,1,req,name=OK" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessageListServiceStatus) Reset()         { *m = ChatMessageListServiceStatus{} }
func (m *ChatMessageListServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ChatMessageListServiceStatus) ProtoMessage()    {}
func (*ChatMessageListServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d4f5b9c2cc7ae31, []int{2}
}

func (m *ChatMessageListServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessageListServiceStatus.Unmarshal(m, b)
}
func (m *ChatMessageListServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessageListServiceStatus.Marshal(b, m, deterministic)
}
func (m *ChatMessageListServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessageListServiceStatus.Merge(m, src)
}
func (m *ChatMessageListServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ChatMessageListServiceStatus.Size(m)
}
func (m *ChatMessageListServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessageListServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessageListServiceStatus proto.InternalMessageInfo

func (m *ChatMessageListServiceStatus) GetOK() bool {
	if m != nil && m.OK != nil {
		return *m.OK
	}
	return false
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "proto_gen.ChatMessage")
	proto.RegisterType((*ChatMessageList)(nil), "proto_gen.ChatMessageList")
	proto.RegisterType((*ChatMessageListServiceStatus)(nil), "proto_gen.ChatMessageListServiceStatus")
}

func init() { proto.RegisterFile("ChatMessageTmp.proto", fileDescriptor_7d4f5b9c2cc7ae31) }

var fileDescriptor_7d4f5b9c2cc7ae31 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x71, 0xce, 0x48, 0x2c,
	0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0xc9, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x04, 0x53, 0xf1, 0xe9, 0xa9, 0x79, 0x4a, 0xd1, 0x5c, 0xdc, 0x48, 0x4a, 0x84, 0x24,
	0xb8, 0xd8, 0x73, 0x21, 0x4c, 0x09, 0x46, 0x05, 0x26, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x88,
	0x8b, 0xa5, 0x24, 0x33, 0x37, 0x55, 0x82, 0x49, 0x81, 0x49, 0x83, 0x39, 0x08, 0xcc, 0x16, 0x92,
	0xe3, 0xe2, 0x4a, 0xce, 0x48, 0x2c, 0x09, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0x93, 0x60, 0x06, 0x6b,
	0x40, 0x12, 0x51, 0xf2, 0xe5, 0xe2, 0x47, 0x32, 0xdc, 0x27, 0xb3, 0xb8, 0x44, 0xc8, 0x8a, 0x8b,
	0x27, 0x19, 0x21, 0x54, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa6, 0x07, 0x77, 0x91,
	0x1e, 0x92, 0x8e, 0x20, 0x14, 0xb5, 0x4a, 0x7a, 0x5c, 0x32, 0x68, 0xc6, 0x05, 0xa7, 0x16, 0x95,
	0x65, 0x26, 0xa7, 0x06, 0x97, 0x24, 0x96, 0x94, 0x16, 0x0b, 0xf1, 0x71, 0x31, 0xf9, 0x7b, 0x83,
	0xdd, 0xcd, 0x11, 0xc4, 0xe4, 0xef, 0x6d, 0x54, 0xca, 0x25, 0x86, 0x5d, 0xbd, 0x50, 0x34, 0x97,
	0x50, 0x40, 0x69, 0x09, 0xba, 0xdb, 0xa4, 0xb0, 0xbb, 0x02, 0x24, 0x27, 0xa5, 0x8e, 0x5b, 0x0e,
	0xc5, 0x11, 0x4a, 0x0c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xfa, 0xa4, 0x5f, 0x74, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatMessageListServiceClient is the client API for ChatMessageListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatMessageListServiceClient interface {
	PutChatMessageList(ctx context.Context, in *ChatMessageList, opts ...grpc.CallOption) (*ChatMessageListServiceStatus, error)
}

type chatMessageListServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatMessageListServiceClient(cc *grpc.ClientConn) ChatMessageListServiceClient {
	return &chatMessageListServiceClient{cc}
}

func (c *chatMessageListServiceClient) PutChatMessageList(ctx context.Context, in *ChatMessageList, opts ...grpc.CallOption) (*ChatMessageListServiceStatus, error) {
	out := new(ChatMessageListServiceStatus)
	err := c.cc.Invoke(ctx, "/proto_gen.ChatMessageListService/PutChatMessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatMessageListServiceServer is the server API for ChatMessageListService service.
type ChatMessageListServiceServer interface {
	PutChatMessageList(context.Context, *ChatMessageList) (*ChatMessageListServiceStatus, error)
}

// UnimplementedChatMessageListServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatMessageListServiceServer struct {
}

func (*UnimplementedChatMessageListServiceServer) PutChatMessageList(ctx context.Context, req *ChatMessageList) (*ChatMessageListServiceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutChatMessageList not implemented")
}

func RegisterChatMessageListServiceServer(s *grpc.Server, srv ChatMessageListServiceServer) {
	s.RegisterService(&_ChatMessageListService_serviceDesc, srv)
}

func _ChatMessageListService_PutChatMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageListServiceServer).PutChatMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_gen.ChatMessageListService/PutChatMessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageListServiceServer).PutChatMessageList(ctx, req.(*ChatMessageList))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatMessageListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_gen.ChatMessageListService",
	HandlerType: (*ChatMessageListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutChatMessageList",
			Handler:    _ChatMessageListService_PutChatMessageList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ChatMessageTmp.proto",
}
